layout(std430, binding = 0) buffer Buffer_Radiance { vec4 radiance[]; };

layout(binding = 0, rgba16f) uniform image2D imgHistory;

void main() {
	const ivec2 px = ivec2(gl_GlobalInvocationID.xy);
	const int linearIdx = px.y * skResolution.x + px.x;
	const vec4 col = radiance[linearIdx];
	const vec4 hist = imageLoad(imgHistory, px);
	// const vec4 accum = mix(hist, col, 1.0 / 16.0);
	const vec4 accum = col;
	imageStore(imgHistory, px, col);
}
