#line 2
layout(binding = 0, rgba16f) writeonly uniform image2D imgWrite;
layout(binding = 2) uniform sampler2D sampRead;
uniform int uPassIndex;

void main() {
	ivec2 px = ivec2(gl_GlobalInvocationID.xy);
	f32v2 uv = (f32v2(px) + 0.5f) / f32v2(skResolution);
	f32 offset = f32(uPassIndex) + 0.5f;
	f32v2 texel = 1.0f / f32v2(skResolution);

	f32v3 col = texture(sampRead, uv + f32v2( offset,  offset) * texel).rgb;
	col      += texture(sampRead, uv + f32v2(-offset,  offset) * texel).rgb;
	col      += texture(sampRead, uv + f32v2( offset, -offset) * texel).rgb;
	col      += texture(sampRead, uv + f32v2(-offset, -offset) * texel).rgb;
	col /= 4.0f;

	imageStore(imgWrite, px, f32v4(col, 1.0f));
}
