#line 1
layout(std430, binding = 0) buffer Buffer_GBuffer {
	GBuffer data[];
};

uniform float uKnob0;
uniform float uKnob1;
uniform float uKnob2;

void main() {
	// for now just write dummy data
	ivec2 px = ivec2(gl_GlobalInvocationID.xy);
	if (any(greaterThanEqual(px, ivec2(skResolution)))) { return; }

	int linearIdx = px.y * skResolution.x + px.x;

	// -- reconstruct UV
	vec2 uv = -1.0f + 2.0f * (vec2(px) + 0.5f) / vec2(skResolution);

	// -- construct seed
	float seed = fract(float(linearIdx) + 1.0f);

	// -- primary ray
	f32 wrapX = uKnob0*6.28318;
	Ray eye = fnLookAtRay(uv, f32v3(cos(wrapX), uKnob1, sin(wrapX))*8.0, f32v3(-1.0, 0.0, 0.0));

	// march into scene
	f32v2 hit = fnSceneMarch(eye);

	f32v3 col = vec3(0.0f);
	if (hit.x > 0.0f) {
		// for now just encode the origin as color
		// just do a simple lambertian shading for now
		f32v3 albedo = f32v3(
			fract(hit.y*1.123912),
			fract(hit.y*2.123912),
			fract(hit.y*3.123912)
		);
		albedo += f32v3(0.2f);
		f32v3 normal = fnSceneNormal(eye.ori + hit.x*eye.dir);
		f32v3 lightDir = normalize(f32v3(0.5f, 1.0f, 0.5f));
		col = albedo * max(dot(normal, lightDir), 0.0f);
	}

	data[linearIdx].ori = vec4(col, 1.0f);
}
