#line 2
layout(std430, binding = 0) buffer Buffer_GBuffer {
	GBuffer data[];
};
layout(std430, binding = 1) buffer Buffer_Light { Light inLight[]; };

f32v2 fnSceneMapLights(f32v3 o) {
	f32v2 res = f32v2(999999.0f, -1.0f);
	for (int i = 0; i < skLightsMax; ++i) {
		if (
			   inLight[i].emission.x <= 0.0f
			&& inLight[i].emission.y <= 0.0f
			&& inLight[i].emission.z <= 0.0f
		) {
			break;
		}
		const Light l = inLight[i];
		const f32v3 up = (
			l.nor.y > 0.99f ? f32v3(0.0, 0.0, 1.0) : f32v3(0.0, 1.0, 0.0)
		);
		const f32v3 ori = inverse(fnLookAt(l.nor, up)) * (o - l.ori);

		Union(res, sdBox(ori, f32v3(0.01, l.halfExtent)), 100.0 + float(i));
	}
	return res;
}

void main() {
	// for now just write dummy data
	ivec2 px = ivec2(gl_GlobalInvocationID.xy);
	if (any(greaterThanEqual(px, ivec2(skResolution)))) { return; }

	int linearIdx = px.y * skResolution.x + px.x;

	// -- reconstruct UV
	vec2 uv = -1.0f + 2.0f * (vec2(px) + 0.5f) / vec2(skResolution);
	uv.x /= skResolution.y / float(skResolution.x);

	// -- construct seed
	float seed = fnSampleSeed(px);

	// -- jitter UV
	uv += (
		(fnSampleUniform2(seed) - 0.5f) * 2.0f / vec2(skResolution)
	);

	// -- primary ray
#if 0
	f32 wrapX = 0.13*TAU;
	f32 wrapY = 0.69;
	f32 wrapZ = 0.23;
#else
	f32 wrapX = uSlots[24]*TAU;
	f32 wrapZ = uSlots[25];
	f32 fov = uSlots[16]*20.0f;
	f32 wrapY = uSlots[20]*2.0;
	f32 targetX = uSlots[17]*2.0f - 1.0f;
	f32 targetY = uSlots[18]*2.0f - 1.0f;
	f32 targetZ = uSlots[19]*2.0f - 1.0f;
#endif
	f32v3 cameraOri = f32v3(cos(wrapX), wrapY, sin(wrapX))*wrapZ*32.0;
	Ray eye = fnLookAtRay(uv, cameraOri, f32v3(targetX,targetY,targetZ), fov);

	// -- march into scene
	f32v2 hit = fnSceneMarch(eye);
	f32v3 ori = eye.ori + eye.dir * hit.x;

	// -- store results
	data[linearIdx].ori = ori;
	data[linearIdx].nor = fnSceneNormal(ori);
	data[linearIdx].hitDist = hit.x;
	data[linearIdx].materialId = hit.y;
	data[linearIdx].wi = eye.dir;
}
