#line 2
layout(std430, binding = 0) buffer Buffer_Palette { vec4 palette[]; };
layout(std430, binding = 1) buffer Buffer_Material { Material material[]; };
layout(std430, binding = 2) buffer Buffer_Light { Light light[]; };

FnSceneMapStub;

void main() {
	uint i = gl_GlobalInvocationID.x*8 + gl_GlobalInvocationID.y;
	if (i >= 256u) return;
	palette[i] = vec4(float(i) / 255.0, float(i) / 255.0, float(i) / 255.0, 1.0);
	palette[i] = pow(palette[i], vec4(2.2));

	// -- light
	if (i == 0u) {
		light[0].ori = NOR3(f32v3(0.54, 0.54, 0.54))*32.0;
		light[0].nor = normalize(NOR3(f32v3(0.54, 0.54, 0.58)));
		light[0].halfExtent = f32v2(1.0, 0.82)*2.0f;
		light[0].emission = vec3(1.0, 1.0, 1.0) * 1000.0 * 0.13;
	}

	light[skLightsInScene].emission = vec3(-1000000.0f);

	// -- material

	// common material
	#define MTRL_GRAYMETAL(i) \
		material[i].albedo = vec3(0.96, 0.96, 1.0) * albedoMult; \
		material[i].alpha = 0.01*0.01; \
		material[i].diffuse = 0.05*0.05; \
		material[i].transmittive = 0.0; \
		material[i].fresnel = 0.5*0.5;

	#define MTRL_GOLD(i) \
		material[i].albedo = vec3(1.0, 0.76, 0.05) * albedoMult; \
		material[i].alpha = 0.17; \
		material[i].diffuse = 0.01; \
		material[i].transmittive = 0.0; \
		material[i].fresnel = 0.63*0.63;

	#define albedoMult IPI
	// -- material setup, just one thread
	if (i == 0u) {
		material[0].albedo = vec3(0.11f, 0.55f, 0.21f) * albedoMult;
		material[0].alpha = 0.2;
		material[0].diffuse = 0.01;
		material[0].transmittive = 0.0;
		material[0].fresnel = 0.3;


		MTRL_GRAYMETAL(1);
		MTRL_GRAYMETAL(2);
		MTRL_GRAYMETAL(3);
		MTRL_GRAYMETAL(4);

		MTRL_GOLD(5);
		MTRL_GRAYMETAL(6);
		MTRL_GRAYMETAL(7);
	}

	#define TUNE_MATERIAL 0
	#define TUNE_MATERIAL_ID 0

	#if TUNE_MATERIAL > 0
	if (i == 0u) {
		material[TUNE_MATERIAL_ID].albedo = vec3(knob3(0));
		material[TUNE_MATERIAL_ID].alpha = uSlots[4]*uSlots[4];
		material[TUNE_MATERIAL_ID].diffuse = uSlots[8]*uSlots[8];
		material[TUNE_MATERIAL_ID].fresnel = uSlots[9]*uSlots[9];
	}
	#endif
}
