layout(binding = 0, rgba16f) uniform image2D imgOut;

layout(binding = 0) uniform sampler2D imgHistory;

uniform float uKnob0;
uniform float uKnob1;
uniform float uKnob2;

// -----------------------------------------------------------------------------
// -- DEBUG STRIP ME OUT
// -----------------------------------------------------------------------------

float DigitBin( const int x )
{
    return x==0?
	 	480599.0:x==1?
		139810.0:x==2?
		476951.0:x==3?
		476999.0:x==4?
		350020.0:x==5?
		464711.0:x==6?
		464727.0:x==7?
		476228.0:x==8?
		481111.0:x==9?
		481095.0:0.0;
}

float PrintValue( vec2 vStringCoords, float fValue, float fMaxDigits, float fDecimalPlaces )
{
	if ((vStringCoords.y < 0.0) || (vStringCoords.y >= 1.0)) return 0.0;

	bool bNeg = ( fValue < 0.0 );
	fValue = abs(fValue);

	float fLog10Value = log2(abs(fValue)) / log2(10.0);
	float fBiggestIndex = max(floor(fLog10Value), 0.0);
	float fDigitIndex = fMaxDigits - floor(vStringCoords.x);
	float fCharBin = 0.0;
	if(fDigitIndex > (-fDecimalPlaces - 1.01)) {
	if(fDigitIndex > fBiggestIndex) {
		if((bNeg) && (fDigitIndex < (fBiggestIndex+1.5))) fCharBin = 1792.0;
	} else {
		if(fDigitIndex == -1.0) {
			if(fDecimalPlaces > 0.0) fCharBin = 2.0;
		} else {
				 float fReducedRangeValue = fValue;
				 if(fDigitIndex < 0.0) {
					fReducedRangeValue = fract( fValue );
					fDigitIndex += 1.0;
				}
			float fDigitValue =
				(abs(fReducedRangeValue / (pow(10.0, fDigitIndex))));
				fCharBin = DigitBin(int(floor(mod(fDigitValue, 10.0))));
		}
	  }
	}
	return floor(mod((fCharBin / pow(2.0, floor(fract(vStringCoords.x) * 4.0) + (floor(vStringCoords.y * 5.0) * 4.0))), 2.0));
}

float PrintFloat(ivec2 px, vec2 gridPos, float value) {
	vec2 fontSize = vec2(8.0, 12.0);
	vec2 fontOffset = vec2(fontSize.x*5.0f, fontSize.y*1.5f);

	// invert gridPos.y to count from top of screen
	gridPos.y = int(720 / (fontOffset.y) - 3) - gridPos.y;

	// offset px by gridOffset which is in units of characters
	px -= ivec2(gridPos * ivec2(fontOffset));

	// bring the first digit into normalized space
	// currently in (0, 0) -> (1280, 720) space
	vec2 normalized = (vec2(px) - fontOffset) / fontSize;
	return PrintValue(normalized, value, 3.0, 2.0);
}

// -----------------------------------------------------------------------------
// -- PRODUCTION ---------------------------------------------------------------
// -----------------------------------------------------------------------------

void main() {
	// mix history3
	ivec2 px = ivec2(gl_GlobalInvocationID.xy);
	vec4 hist = texture(imgHistory, vec2(px) / vec2(skResolution.y));
	hist = pow(hist, vec4(1.0 / 2.2));

	// print knobs [[DEBUG STRIP ME OUT]]
	{
		float knob = 0.0f;
		knob += PrintFloat(px, vec2(0, 1), uKnob0);
		knob += PrintFloat(px, vec2(1, 1), uKnob1);
		knob += PrintFloat(px, vec2(0.5, 0), uKnob2);

		// invert color
		if (knob > 0.0f) {
			hist = vec4(1.0f) - hist;
		}
	}

	imageStore(imgOut, px, hist);
}
