#line 2
layout(binding = 0, rgba16f) uniform image2D imgOut;

layout(binding = 2) uniform sampler2D samplerHistory;
layout(binding = 3) uniform sampler2D samplerBloom;

FnSceneMapStub;

// -----------------------------------------------------------------------------
// -- DEBUG STRIP ME OUT
// -----------------------------------------------------------------------------

float DigitBin( const int x )
{
    return x==0?
	 	480599.0:x==1?
		139810.0:x==2?
		476951.0:x==3?
		476999.0:x==4?
		350020.0:x==5?
		464711.0:x==6?
		464727.0:x==7?
		476228.0:x==8?
		481111.0:x==9?
		481095.0:0.0;
}

float PrintValue( vec2 vStringCoords, float fValue, float fMaxDigits, float fDecimalPlaces )
{
	if ((vStringCoords.y < 0.0) || (vStringCoords.y >= 1.0)) return 0.0;

	bool bNeg = ( fValue < 0.0 );
	fValue = abs(fValue);

	float fLog10Value = log2(abs(fValue)) / log2(10.0);
	float fBiggestIndex = max(floor(fLog10Value), 0.0);
	float fDigitIndex = fMaxDigits - floor(vStringCoords.x);
	float fCharBin = 0.0;
	if(fDigitIndex > (-fDecimalPlaces - 1.01)) {
	if(fDigitIndex > fBiggestIndex) {
		if((bNeg) && (fDigitIndex < (fBiggestIndex+1.5))) fCharBin = 1792.0;
	} else {
		if(fDigitIndex == -1.0) {
			if(fDecimalPlaces > 0.0) fCharBin = 2.0;
		} else {
				 float fReducedRangeValue = fValue;
				 if(fDigitIndex < 0.0) {
					fReducedRangeValue = fract( fValue );
					fDigitIndex += 1.0;
				}
			float fDigitValue =
				(abs(fReducedRangeValue / (pow(10.0, fDigitIndex))));
				fCharBin = DigitBin(int(floor(mod(fDigitValue, 10.0))));
		}
	  }
	}
	return floor(mod((fCharBin / pow(2.0, floor(fract(vStringCoords.x) * 4.0) + (floor(vStringCoords.y * 5.0) * 4.0))), 2.0));
}

float PrintFloat(ivec2 px, vec2 gridPos, float value, float decimals = 2.0f) {
	vec2 fontSize = vec2(8.0, 12.0);
	vec2 fontOffset = vec2(fontSize.x*5.0f, fontSize.y*1.5f);

	// invert gridPos.y to count from top of screen
	gridPos.y = int(skResolutionY / (fontOffset.y) - 2) - gridPos.y;

	// offset px by gridOffset which is in units of characters
	px -= ivec2(gridPos * ivec2(fontOffset));

	// bring the first digit into normalized space
	// currently in (0, 0) -> (skResolutionX, skResolutionY) space
	vec2 normalized = (vec2(px) - fontOffset) / fontSize;
	return PrintValue(normalized, value, 3.0, decimals);
}

// -----------------------------------------------------------------------------
// -- PRODUCTION ---------------------------------------------------------------
// -----------------------------------------------------------------------------

void main() {
	// mix history
	ivec2 px = ivec2(gl_GlobalInvocationID.xy);
	vec4 hist = texture(samplerHistory, vec2(px) / vec2(skResolution));

	// print knobs [[DEBUG STRIP ME OUT]]
	{
		float knob = 0.0f;
		knob += PrintFloat(px, vec2(1, 1), uKnobR);
		knob += PrintFloat(px, vec2(12.5, 0), iTime);
		knob += PrintFloat(px, vec2(12.5, 1), iFrame);
		knob += PrintFloat(px, vec2(12.5, 2), iMillis);

		// print each slot
		int activeSlots = 0;
		for (int i = 0; i < 64; ++i) {
			if (uSlots[i] < 0.001f) {
				continue;
			}

			knob += (
				PrintFloat(
					px,
					vec2(-1.0, 2) + vec2(0.0f, float(activeSlots)),
					float(i),
					0.0f
				)
			);

			knob += (
				PrintFloat(
					px,
					vec2(-0.5, 2) + vec2(0.0f, float(activeSlots)),
					uSlots[i]
				)
			);

			++activeSlots;
		}

		// invert color
		if (knob > 0.0f) {
			hist = vec4(1.0f) - hist;
			hist += vec4(0.2f);
		}
	}

	f32v2 uv = (f32v2(px) + 0.5f) / vec2(skResolution);

	// -- brightness
	hist.rgb *= pow(2.0f, (uKnobR * 2.0f - 1.0f)*5.0f);

	// -- bloom
	{
		f32v3 col = texture(samplerBloom, uv).rgb;
		hist.rgb += col*0.24f;
	}

	// -- tonemap
	{
		const f32 a = 2.51f;
		const f32 b = 0.03f;
		const f32 c = 2.43f;
		const f32 d = 0.59f;
		const f32 e = 0.14f;
		const f32v3 x = hist.rgb;
		hist.rgb = (
			clamp((x*(a*x + b))/(x*(c*x + d) + e), f32v3(0.0f), f32v3(1.0f))
		);
		hist.rgb = pow(hist.rgb, vec3(1.0f/2.2f));
	}


	// -- vignette to hide temporal artifacts
	{
		f32v2 uvNor = uv*2.0f - 1.0f;
		f32v2 vig2 = smoothstep(f32v2(1.0f), f32v2(0.1f), abs(uvNor));
		f32 vignette = vig2.x * vig2.y;
		vignette = pow(vignette, 0.4f);
		hist.rgb *= vignette;
	}

	imageStore(imgOut, px, vec4(hist.rgb, 1.0f));
}
